# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



target 'BlindTune' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!=
  pod 'ReachabilitySwift'
  pod 'NVActivityIndicatorView'
  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'GrowingTextView', '0.7.0'
  pod 'ZLSinusWaveView' 
  pod 'Mixpanel-swift'

  # Pods for BlindTune

end
